title: Pages with Jekyll
author: Awayken
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I love stuff.

# social links
twitter_username: awayken
github_username:  awayken

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
